# Generated by Django 4.1.2 on 2022-10-11 00:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        
    ]
